import puppeteer from "puppeteer";
import fs from "fs";
import { getGodDetails } from "./functions.js";

//Set headless to true if you want to hide window
const browser = await puppeteer.launch({ headless: false });
const page = await browser.newPage();

await page.goto('https://www.smitegame.com/gods?lng=fr_FR')
await page.waitForSelector('.single__god', { timeout: 3000 });

const godsUrl = await page.$$eval('.single__god', gods => gods.map(god => god.href));
const newGodUrl = await page.$eval('.single__god--new', god => god.href);

await page.close();

//Get informations about gods in new page
const cluster = async (arrUrl) => {
    const gods = [];
    const page = await browser.newPage();
    for (const url of arrUrl) {
        gods.push(await getGodDetails(url, page))
    }
    return gods;
};

//Divide gods array into smaller arrays, their sizes are defined by chunkSize. Example: 12 = 12 gods in one array
function sliceIntoChunks(arr, chunkSize) {
    const res = [];
    for (let i = 0; i < arr.length; i += chunkSize) {
        const chunk = arr.slice(i, i + chunkSize);
        res.push(cluster(chunk));
    }
    return res;
};

/*Execute promises in concurrency. For each chunks generated by sliceIntoChunks a new page will be created an 
get informations about gods chunks array. If you have a powerful computer, you can decrease chunkSize. It going to create more chunks
and increase cluster number so more page and more work in concurrency. 
*/
const gods = await Promise.all(sliceIntoChunks([newGodUrl, ...godsUrl], 12));
await browser.close();

fs.writeFile('gods.json', JSON.stringify(gods.flat(), null, 2), (err) => {
    if (err) throw err;
    console.log('Data written to file');
});


